# Website Configuration
title: Fortunato.pro
description: Exploring the World of IT and Geek Culture
author: Fortunato.pro
theme: geek-theme
language: en-US

# Navigation
navigation:
  - label: Home
    url: /
  - label: Articles
    url: /articles
  - label: Reviews
    url: /reviews
  - label: Tutorials
    url: /tutorials
  - label: About
    url: /about

# Homepage Sections
sections:
  - type: hero
    title: Welcome to Fortunato.pro
    subtitle: Embrace Your Inner Geek
    image: assets/images/hero-image.jpg

  - type: features
    title: What We Offer
    features:
      - title: Tech News
        description: Stay up-to-date with the latest trends and news from the world of technology.
        icon: fas fa-newspaper

      - title: Reviews
        description: In-depth reviews of gadgets, software, and geeky products.
        icon: fas fa-star

      - title: Tutorials
        description: Step-by-step guides to help you master various IT skills and geeky projects.
        icon: fas fa-code

  - type: articles
    title: Latest Articles
    limit: 3

  - type: subscribe
    title: Join Our Geek Community
    subtitle: Subscribe to our newsletter and never miss an update!
    buttonText: Subscribe Now

# Footer Information
footer:
  copyright: © 2023 Fortunato.pro. All rights reserved.
  social:
    - name: Twitter
      icon: fab fa-twitter
      url: https://www.twitter.com/fortunatopro

    - name: YouTube
      icon: fab fa-youtube
      url: https://www.youtube.com/fortunatopro

    - name: Instagram
      icon: fab fa-instagram
      url: https://www.instagram.com/fortunatopro

