# This is a scalars type (strings)
apiVersion: v1
kind: Pod
# This is a exemplo of Dictionary, so everything under the metadata is intended to the right
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
