apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myapp
    tier: front-end
spec:
  template:
    containers:
    - name: nginx-container
      image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end